name: EconomyBank
main: EconomyBank\main
version: 1.0.3
api: 3.4.0
load: POSTWORLD
author: PJZ9n
authors: [narapon]
desctiption: PMMP EconomyBank Plugin
website: http://asvd.net/
permissions:
  economybank:
    default: op
    description: "Allows using all the EconomyBank things"
    children:
      economybank.command:
        default: op
        description: "Allows using all the EconomyBank commands"
        children:
          economybank.command.bank:
            default: true
            description: "Allows all the bank command"
